#!/usr/bin/env bash
# php-mysql.sh — адаптер для PHP+MySQL+Apache (elsesserandco)

set -euo pipefail

adapter_name() {
  echo "php-mysql"
}

adapter_matches() {
  local stack_json="$1"
  local entry; entry=$(echo "$stack_json" | jq -r '.entry_type' 2>/dev/null)
  local db;    db=$(echo "$stack_json"    | jq -r '.db' 2>/dev/null)
  [[ "$entry" == "php" && "$db" == "mysql" ]]
}

adapter_describe() {
  cat <<EOF
PHP 8.1 + FPM
MySQL 8 / MariaDB
Apache 2.4 + mod_rewrite
Let's Encrypt (опционально)
EOF
}

adapter_apt_packages() {
  cat <<EOF
php8.1-cli
php8.1-fpm
php8.1-mysql
php8.1-curl
php8.1-mbstring
php8.1-xml
php8.1-zip
php8.1-gd
php8.1-bcmath
php8.1-intl
mysql-client
apache2
libapache2-mod-fcgid
certbot
python3-certbot-apache
EOF
}

adapter_apache_modules() {
  echo "rewrite headers deflate expires proxy_fcgi setenvif ssl"
}

# adapter_vhost_template <domain> <webroot> <project_path> <php_mode> <ssl>
adapter_vhost_template() {
  local domain="$1" webroot="$2" project_path="$3" php_mode="$4" ssl="$5"
  cat <<EOF
# Generated by site-install on $(date -Iseconds)
<VirtualHost *:80>
    ServerName ${domain}
    ServerAlias www.${domain}
    DocumentRoot ${webroot}

    <Directory ${webroot}>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch "\.php$">
        SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
    </FilesMatch>

    ErrorLog \${APACHE_LOG_DIR}/${domain}-error.log
    CustomLog \${APACHE_LOG_DIR}/${domain}-access.log combined
</VirtualHost>
EOF
}

# adapter_env_prompts <app_url>
# Возвращает многострочный список key|label|default
adapter_env_prompts() {
  local app_url="${1:-http://localhost}"
  cat <<EOF
APP_URL|Application URL|${app_url}
APP_ENV|Application environment|production
REALESTATE_DB_HOST|DB host|localhost
REALESTATE_DB_NAME|DB name|realestate_db
REALESTATE_DB_USER|DB user|realestate_user
REALESTATE_DB_PASS|DB password|
REALESTATE_DB_CHARSET|DB charset|utf8mb4
MAIL_TRANSPORT|Mail transport (smtp/mail/log)|log
MAIL_HOST|SMTP host|smtp.yandex.ru
MAIL_PORT|SMTP port|465
MAIL_USERNAME|SMTP username|
MAIL_PASSWORD|SMTP password|
MAIL_ENCRYPTION|Encryption (ssl/tls/empty)|ssl
MAIL_FROM_ADDRESS|From email|noreply@example.com
MAIL_FROM_NAME|From name|Elsesser & Co.
VK_CLIENT_ID|VK Client ID (optional)|
YANDEX_CLIENT_ID|Yandex Client ID (optional)|
GOOGLE_CLIENT_ID|Google Client ID (optional)|
TELEGRAM_BOT_TOKEN|Telegram Bot Token (optional)|
VAPID_PUBLIC_KEY|VAPID public key (optional)|
VAPID_PRIVATE_KEY|VAPID private key (optional)|
VAPID_SUBJECT|VAPID subject|mailto:admin@example.com
YANDEX_MAPS_API_KEY|Yandex Maps API key (optional)|
EOF
}

adapter_post_install() {
  local project_path="$1"
  # composer install если есть composer.json
  if [[ -f "$project_path/composer.json" ]] && command -v composer >/dev/null 2>&1; then
    (cd "$project_path" && composer install --no-dev --optimize-autoloader 2>&1) || true
  fi
}

adapter_migrate() {
  local project_path="$1"
  (cd "$project_path" && php database/migrate.php)
}
