#!/usr/bin/env bash
# apache.sh — настройка Apache

set -euo pipefail

# Включить модули (только отсутствующие)
enable_apache_modules() {
  local -a modules=("$@")
  local -a to_enable
  local enabled
  enabled=$(a2query -m 2>/dev/null | sort -u || true)

  for mod in "${modules[@]}"; do
    grep -qxF "$mod" <<< "$enabled" || to_enable+=("$mod")
  done

  if [[ ${#to_enable[@]} -eq 0 ]]; then
    log_skip "apache: все модули уже включены"
    return 0
  fi

  local -a steps=(
    "a2enmod ${to_enable[*]}"
    "systemctl reload apache2"
  )
  run_with_progress "Включение модулей Apache" "${#steps[@]}" "${steps[@]}"
}

# Создать VirtualHost
# make_vhost <domain> <webroot_abs> <project_path> <php_mode: fpm|mod_php> <ssl: yes|no>
make_vhost() {
  local domain="$1" webroot_abs="$2" project_path="$3" php_mode="$4" ssl="$5"
  local vhost_file="/etc/apache2/sites-available/${domain}.conf"

  cat <<EOF
# Generated by site-install on $(date -Iseconds)
<VirtualHost *:80>
    ServerName ${domain}
    ServerAlias www.${domain}
    DocumentRoot ${webroot_abs}

    <Directory ${webroot_abs}>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch "\.php$">
        SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
    </FilesMatch>

    ErrorLog \${APACHE_LOG_DIR}/${domain}-error.log
    CustomLog \${APACHE_LOG_DIR}/${domain}-access.log combined
</VirtualHost>
EOF
}

# Применить vhost (записать файл, активировать)
apply_vhost() {
  local domain="$1" vhost_content="$2" project_path="$3"

  local vhost_file="/etc/apache2/sites-available/${domain}.conf"
  local -a steps=(
    "echo '$vhost_content' > '$vhost_file'"
    "a2dissite 000-default.conf || true"
    "a2ensite ${domain}.conf"
    "chown -R www-data:www-data '$project_path'"
    "find '$project_path' -type d -not -path '*/.git*' -exec chmod 775 {} \;"
    "find '$project_path' -type f -not -path '*/.git*' -exec chmod 664 {} \;"
  )

  run_with_progress "Настройка VirtualHost" "${#steps[@]}" "${steps[@]}"
}
