#!/usr/bin/env bash
# env.sh — генерация .env из prompts адаптера

set -euo pipefail

# Секреты — поля с этими именами идут через passwordbox
SECRET_FIELDS=(
  "REALESTATE_DB_PASS"
  "MAIL_PASSWORD"
  "VK_CLIENT_SECRET"
  "YANDEX_CLIENT_SECRET"
  "GOOGLE_CLIENT_SECRET"
  "TELEGRAM_BOT_TOKEN"
  "VAPID_PRIVATE_KEY"
)

is_secret_field() {
  local key="$1"
  for s in "${SECRET_FIELDS[@]}"; do
    [[ "$s" == "$key" ]] && return 0
  done
  return 1
}

# Escape значения для .env (если есть спецсимволы — обернуть в кавычки)
escape_env_value() {
  local value="$1"
  if [[ "$value" =~ [[:space:]] ]] || [[ "$value" =~ \# ]] || [[ "$value" =~ \" ]]; then
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '"%s"' "$value"
  else
    printf '%s' "$value"
  fi
}

# Сгенерировать .env из prompts
# generate_env <project_path> <prompts_string>
# prompts_string — многострочный, формат: key|label|default на каждой строке
generate_env() {
  local project_path="$1" prompts="$2"
  local env_file="$project_path/.env"
  local tmp; tmp=$(mktemp)

  {
    echo "# Generated by site-install on $(date -Iseconds)"
    echo "# Do not commit this file."
    echo ""
  } > "$tmp"

  while IFS='|' read -r key label default; do
    [[ -z "$key" || "$key" =~ ^# ]] && continue

    local value
    if is_secret_field "$key"; then
      value=$(ui_password "$label" 2>/dev/null || echo "")
      [[ -z "$value" && -n "$default" ]] && value="$default"
    else
      value=$(ui_input "$label" "$default" 2>/dev/null || echo "$default")
    fi

    echo "${key}=$(escape_env_value "$value")" >> "$tmp"
  done <<< "$prompts"

  mv "$tmp" "$env_file"
  chmod 600 "$env_file"
  ok ".env создан: $env_file"
}
